server.port=8080
# Veritaban? ba?lant? adresi (sondaki s18d4 olu?turdu?un db ismi olmal?)
spring.datasource.url=jdbc:postgresql://localhost:5432/s18d4
# PostgreSQL kullan?c? ad?n (genelde postgreste kal?r)
spring.datasource.username=postgres
# Kurulumda belirledi?in ?ifre (Buras? çok önemli!)
spring.datasource.password=hello 

# Tablolar? Hibernate otomatik olu?tursun diye:
spring.jpa.hibernate.ddl-auto=update